// glossaryファイル English_conversation
`use strict`
const glossary = [
{target:`Hello. `, content:`こんにちは。`},
{target:`Hi. `, content:`やあ。`},
{target:`Good morning. `, content:`おはようございます。`},
{target:`Good afternoon. `, content:`こんにちは。`},
{target:`Good evening. `, content:`こんばんは。`},
{target:`How are you? `, content:`お元気ですか？`},
{target:`I'm fine, thank you. `, content:`元気です、ありがとう。`},
{target:`What's your name? `, content:`あなたの名前は何ですか？`},
{target:`My name is [Your Name]. `, content:`私の名前は［あなたの名前］です。`},
{target:`Nice to meet you. `, content:`お会いできて嬉しいです。`},
{target:`Goodbye. `, content:`さようなら。`},
{target:`See you later. `, content:`またね。`},
{target:`Please. `, content:`どうぞ。`},
{target:`Thank you. `, content:`ありがとう。`},
{target:`You're welcome. `, content:`どういたしまして。`},
{target:`Excuse me. `, content:`すみません。`},
{target:`I'm sorry. `, content:`ごめんなさい。`},
{target:`No problem. `, content:`問題ありません。`},
{target:`Yes. `, content:`はい。`},
{target:`No. `, content:`いいえ。`},
{target:`Maybe. `, content:`たぶん。`},
{target:`I don't know. `, content:`わかりません。`},
{target:`Can you help me? `, content:`助けてもらえますか？`},
{target:`Of course. `, content:`もちろん。`},
{target:`I'm lost. `, content:`道に迷いました。`},
{target:`Where is the bathroom? `, content:`トイレはどこですか？`},
{target:`How much does this cost? `, content:`これはいくらですか？`},
{target:`What time is it? `, content:`今何時ですか？`},
{target:`Do you speak English? `, content:`英語を話せますか？`},
{target:`I don't understand. `, content:`わかりません。`},
{target:`Can you repeat that, please? `, content:`もう一度言っていただけますか？`},
{target:`What do you do? `, content:`仕事は何をしていますか？`},
{target:`Where are you from? `, content:`出身はどちらですか？`},
{target:`How long have you been here? `, content:`ここにどれくらいいましたか？`},
{target:`What's the weather like today? `, content:`今日の天気はどうですか？`},
{target:`It's hot/cold. `, content:`暑い／寒いです。`},
{target:`I like [something]. `, content:`［何か］が好きです。`},
{target:`I don't like [something]. `, content:`［何か］が嫌いです。`},
{target:`What are your hobbies? `, content:`趣味は何ですか？`},
{target:`I love to [activity]. `, content:`［アクティビティ］が大好きです。`},
{target:`I enjoy [activity]. `, content:`［アクティビティ］を楽しんでいます。`},
{target:`How was your day? `, content:`今日はどうでしたか？`},
{target:`It was good/bad. `, content:`良かった／悪かったです。`},
{target:`What are your plans for the weekend? `, content:`週末の予定は何ですか？`},
{target:`I'm going to [place/activity]. `, content:`［場所／アクティビティ］に行くつもりです。`},
{target:`Can I have the bill, please? `, content:`お会計お願いします。`},
{target:`What do you recommend? `, content:`何がおすすめですか？`},
{target:`I'll have [dish]. `, content:`［料理］をください。`},
{target:`Can I get a coffee, please? `, content:`コーヒーをもらえますか？`},
{target:`How do you spell that? `, content:`それはどう綴りますか？`},
{target:`What's your phone number? `, content:`電話番号は何ですか？`},
{target:`Where do you live? `, content:`どこに住んでいますか？`},
{target:`I live in [city/country]. `, content:`［市／国］に住んでいます。`},
{target:`What's your favorite movie/book? `, content:`お気に入りの映画／本は何ですか？`},
{target:`Can I take a photo? `, content:`写真を撮ってもいいですか？`},
{target:`How do I get to [place]? `, content:`［場所］へはどう行けばいいですか？`},
{target:`I need a doctor. `, content:`医者が必要です。`},
{target:`Where is the nearest pharmacy? `, content:`最寄りの薬局はどこですか？`},
{target:`Happy birthday! `, content:`お誕生日おめでとうございます！`},
{target:`Congratulations! `, content:`おめでとうございます！`},
{target:`I'm so sorry to hear that. `, content:`それを聞いてとても残念です。`},
{target:`What's new? `, content:`最近どう？`},
{target:`That's interesting. `, content:`それは面白いね。`},
{target:`Can I borrow a pen? `, content:`ペンを借りてもいいですか？`},
{target:`Do you have any plans for tonight? `, content:`今夜の予定はありますか？`},
{target:`Where did you learn English? `, content:`どこで英語を学びましたか？`},
{target:`I'm looking for [something]. `, content:`［何か］を探しています。`},
{target:`Can you recommend a good restaurant? `, content:`おいしいレストランをお勧めできますか？`},
{target:`I'm lost. Can you help me find my way? `, content:`道に迷いました。道案内してくれますか？`},
{target:`What's the best way to get there? `, content:`そこへの一番良い行き方は何ですか？`},
{target:`It's a beautiful day, isn't it? `, content:`いい天気ですね。`},
{target:`What do you think about [topic]? `, content:`［トピック］についてどう思いますか？`},
{target:`I'm not sure. `, content:`よくわかりません。`},
{target:`Can you speak more slowly, please? `, content:`もう少しゆっくり話していただけますか？`},
{target:`What's the meaning of [word]? `, content:`［単語］の意味は何ですか？`},
{target:`I don't understand the instructions. `, content:`説明が理解できません。`},
{target:`Could you please explain that again? `, content:`もう一度説明していただけますか？`},
{target:`I have a question. `, content:`質問があります。`},
{target:`Can I ask you something? `, content:`何か質問してもいいですか？`},
{target:`What's the deadline for this project? `, content:`このプロジェクトの締め切りはいつですか？`},
{target:`Can I have a day off tomorrow? `, content:`明日休みをもらえますか？`},
{target:`I'm running late. `, content:`遅れています。`},
{target:`How was your weekend? `, content:`週末はどうでしたか？`},
{target:`What's your favorite type of music? `, content:`お気に入りの音楽のジャンルは何ですか？`},
{target:`I have a headache. `, content:`頭痛がします。`},
{target:`Can I have some water, please? `, content:`水をもらえますか？`},
{target:`What's the best way to learn a new language? `, content:`新しい言語を学ぶ一番良い方法は何ですか？`},
{target:`I'm looking for a hotel. `, content:`ホテルを探しています。`},
{target:`How much is the entrance fee? `, content:`入場料はいくらですか？`},
{target:`What's your favorite season? `, content:`お気に入りの季節は何ですか？`},
{target:`Do you have any siblings? `, content:`兄弟姉妹はいますか？`},
{target:`How do you spend your weekends? `, content:`週末はどのように過ごしますか？`},
{target:`I love to travel. `, content:`旅行が大好きです。`},
{target:`What's the best place you've ever visited? `, content:`訪れたことのある場所で一番良かったところはどこですか？`},
{target:`I'm a vegetarian. `, content:`私はベジタリアンです。`},
{target:`Can I have the check, please? `, content:`お勘定をお願いします。`},
{target:`What do you do for a living? `, content:`生計を立てるために何をしていますか？`},
{target:`Can you recommend a good book? `, content:`おすすめの本を教えてもらえますか？`},
{target:`I'm really enjoying our conversation. `, content:`この会話をとても楽しんでいます。`},
{target:`Break a leg. `, content:`頑張ってね。`},
{target:`Bite the bullet. `, content:`我慢する、困難に立ち向かう。`},
{target:`Burn the midnight oil. `, content:`夜遅くまで働く。`},
{target:`Cost an arm and a leg. `, content:`非常に高価である。`},
{target:`Piece of cake. `, content:`簡単なこと。`},
{target:`Hit the nail on the head. `, content:`要点をつく、正確な指摘をする。`},
{target:`It's raining cats and dogs. `, content:`大雨が降っている。`},
{target:`Jump on the bandwagon. `, content:`流行に乗る、他にもやる人がいるからやる。`},
{target:`Let the cat out of the bag. `, content:`秘密を漏らす。`},
{target:`A piece of cake. `, content:`とても簡単なこと。`},
{target:`Out of the blue. `, content:`突然に。`},
{target:`Under the weather. `, content:`元気がない、体調が悪い。`},
{target:`Kick the bucket. `, content:`亡くなる。`},
{target:`Burn bridges. `, content:`関係を断つ。`},
{target:`Bury the hatchet. `, content:`仲直りする。`},
{target:`Butterflies in my stomach. `, content:`緊張している。`},
{target:`Cry over spilled milk. `, content:`叶わなかったことを嘆く。`},
{target:`Don't count your chickens before they hatch. `, content:`蓋を開ける前に先走るな。`},
{target:`Easy as pie. `, content:`非常に簡単。`},
{target:`Every cloud has a silver lining. `, content:`どんな困難にも良い面がある。`},
{target:`A picture is worth a thousand words. `, content:`言葉よりも画像の方が意味がある。`},
{target:`Face the music. `, content:`責任をとる。`},
{target:`Hit the hay. `, content:`寝る。`},
{target:`It takes two to tango. `, content:`問題や課題は双方にある。`},
{target:`Jumping on the bandwagon. `, content:`流行に乗る。`},
{target:`Keep an eye on the ball. `, content:`注意を払う。`},
{target:`Let sleeping dogs lie. `, content:`問題を起こさないようにする。`},
{target:`Miss the boat. `, content:`チャンスを逃す。`},
{target:`No pain, no gain. `, content:`苦労なくして成功なし。`},
{target:`Off the hook. `, content:`責任が免れる。`},
{target:`Paint the town red. `, content:`楽しい時間を過ごす。`},
{target:`Put all your eggs in one basket. `, content:`リスクを取る。`},
{target:`The ball is in your court. `, content:`決断はあなた次第。`},
{target:`Through thick and thin. `, content:`困難な時でも支え合う。`},
{target:`A penny for your thoughts. `, content:`何を考えているか教えて。`},
{target:`All ears. `, content:`興味津々。`},
{target:`Barking up the wrong tree. `, content:`誤った方向に取り組む。`},
{target:`Burn the midnight oil. `, content:`徹夜で働く。`},
{target:`Cry over spilled milk. `, content:`叶わなかったことを嘆く。`},
{target:`Cut to the chase. `, content:`要点を述べる。`},
{target:`Don't put all your eggs in one basket. `, content:`リスクを分散する。`},
{target:`Easy as pie. `, content:`非常に簡単。`},
{target:`Fit as a fiddle. `, content:`とても健康。`},
{target:`Get cold feet. `, content:`臆病になる。`},
{target:`Hit the hay. `, content:`寝る。`},
{target:`Jump on the bandwagon. `, content:`流行に乗る。`},
{target:`Keep an eye on the ball. `, content:`注意を払う。`},
{target:`Let the cat out of the bag. `, content:`秘密を漏らす。`},
{target:`Make a long story short. `, content:`手短に話す。`},
{target:`No pain, no gain. `, content:`苦労なくして成功なし。`},
{target:`Off the hook. `, content:`責任が免れる。`},
{target:`Pay the piper. `, content:`代償を支払う。`},
{target:`Piece of cake. `, content:`簡単なこと。`},
{target:`Quit cold turkey. `, content:`一度にやめる。`},
{target:`Rule of thumb. `, content:`経験則。`},
{target:`The ball is in your court. `, content:`決断はあなた次第。`},
{target:`Under the weather. `, content:`元気がない、体調が悪い。`},
{target:`Burn the midnight oil. `, content:`夜遅くまで働く。`},
{target:`Bite the bullet. `, content:`困難に立ち向かう。`},
{target:`A dime a dozen. `, content:`ごくありふれたもの。`},
{target:`All ears. `, content:`興味津々。`},
{target:`Break the ice. `, content:`積極的なやり取りを始める。`},
{target:`Cry over spilled milk. `, content:`叶わなかったことを嘆く。`},
{target:`Cut to the chase. `, content:`要点を述べる。`},
{target:`Don't put all your eggs in one basket. `, content:`リスクを分散する。`},
{target:`Every cloud has a silver lining. `, content:`どんな困難にも良い面がある。`},
{target:`Face the music. `, content:`責任をとる。`},
{target:`Get cold feet. `, content:`臆病になる。`},
{target:`Hit the nail on the head. `, content:`要点をつく、正確な指摘をする。`},
{target:`It's raining cats and dogs. `, content:`大雨が降っている。`},
{target:`Jump on the bandwagon. `, content:`流行に乗る。`},
{target:`Keep an eye on the ball. `, content:`注意を払う。`},
{target:`Let the cat out of the bag. `, content:`秘密を漏らす。`},
{target:`Make a long story short. `, content:`手短に話す。`},
{target:`No pain, no gain. `, content:`苦労なくして成功なし。`},
{target:`Off the hook. `, content:`責任が免れる。`},
{target:`Pay the piper. `, content:`代償を支払う。`},
{target:`Piece of cake. `, content:`簡単なこと。`},
{target:`Quit cold turkey. `, content:`一度にやめる。`},
{target:`Rule of thumb. `, content:`経験則。`},
{target:`The ball is in your court. `, content:`決断はあなた次第。`},
{target:`Under the weather. `, content:`元気がない、体調が悪い。`},
{target:`Burn the midnight oil. `, content:`夜遅くまで働く。`},
{target:`Bite the bullet. `, content:`困難に立ち向かう。`},
{target:`A dime a dozen. `, content:`ごくありふれたもの。`},
{target:`All ears. `, content:`興味津々。`},
{target:`Break the ice. `, content:`積極的なやり取りを始める。`},
{target:`Cry over spilled milk. `, content:`叶わなかったことを嘆く。`},
{target:`Cut to the chase. `, content:`要点を述べる。`},
{target:`Don't put all your eggs in one basket. `, content:`リスクを分散する。`},
{target:`Every cloud has a silver lining. `, content:`どんな困難にも良い面がある。`},
{target:`Face the music. `, content:`責任をとる。`},
{target:`Get cold feet. `, content:`臆病になる。`},
{target:`Hit the nail on the head. `, content:`要点をつく、正確な指摘をする。`},
{target:`It's raining cats and dogs. `, content:`大雨が降っている。`},
{target:`Jump on the bandwagon. `, content:`流行に乗る。`},
{target:`Keep an eye on the ball. `, content:`注意を払う。`},
{target:`Let the cat out of the bag. `, content:`秘密を漏らす。`},
{target:`Make a long story short. `, content:`手短に話す。`},
{target:`No pain, no gain. `, content:`苦労なくして成功なし。`},
{target:`Go straight ahead.`, content:`まっすぐ進んでください。`},
{target:`Turn left at the next intersection.`, content:`次の交差点で左に曲がってください。`},
{target:`Turn right after the traffic light.`, content:`信号を過ぎて右に曲がってください。`},
{target:`It's just around the corner.`, content:`すぐ角を曲がったところです。`},
{target:`You're getting close.`, content:`近づいていますね。`},
{target:`Take the second street on the left.`, content:`左に2本目の道を取ってください。`},
{target:`It's on your right-hand side.`, content:`右側にあります。`},
{target:`Cross the bridge and then turn left.`, content:`橋を渡ってから左に曲がってください。`},
{target:`Follow the signs for [place].`, content:`[場所] の案内に従ってください。`},
{target:`You'll pass a park on your right.`, content:`右側に公園があります。`},
{target:`Walk straight for about 10 minutes.`, content:`約10分間まっすぐ歩いてください。`},
{target:`It's a short walk from here.`, content:`ここから歩いてすぐです。`},
{target:`Take the elevator to the third floor.`, content:`エレベーターで3階に行ってください。`},
{target:`The bus stop is in front of the library.`, content:`バス停は図書館の前にあります。`},
{target:`Head towards the city center.`, content:`市街地の方向に進んでください。`},
{target:`The museum is on the opposite side of the street.`, content:`博物館は道路の反対側にあります。`},
{target:`You can't miss it; it's the tall building.`, content:`高い建物なので見逃すことはありません。`},
{target:`Go through the alley, and you'll find it on the left.`, content:`路地を抜けて左側に見つかります。`},
{target:`It's a 15-minute drive from here.`, content:`ここから車で15分です。`},
{target:`Keep going until you see a big red sign.`, content:`大きな赤い看板が見えるまで進んでください。`},
{target:`You'll reach your destination in no time.`, content:`すぐに目的地に到着します。`},
{target:`Follow the curve of the road.`, content:`道路の曲線に従ってください。`},
{target:`It's on the outskirts of town.`, content:`町の外れにあります。`},
{target:`Take the subway going in the direction of [direction].`, content:`[方向] 行きの地下鉄に乗ってください。`},
{target:`It's a bit of a hike, but the view is worth it.`, content:`少し遠いですが、眺めは価値があります。`},
{target:`You're on the right track; keep going.`, content:`正しい方向です。そのまま進んでください。`},
{target:`The street names can be a bit confusing, but don't worry.`, content:`道の名前は少し混乱するかもしれませんが、心配しないでください。`},
{target:`You'll need to make a U-turn at the next intersection.`, content:`次の交差点でＵターンしてください。`},
{target:`It's in the heart of the shopping district.`, content:`ショッピングエリアの中心部にあります。`},
{target:`If you reach the train station, you've gone too far.`, content:`駅に到達したら、行き過ぎています。`},
{target:`How much is this?`, content:`これはいくらですか？`},
{target:`Is there a discount on this item?`, content:`この商品には割引がありますか？`},
{target:`Can I get a receipt, please?`, content:`領収書をもらえますか？`},
{target:`Do you accept credit cards?`, content:`クレジットカードは使えますか？`},
{target:`Is there a sale going on?`, content:`セールは行われていますか？`},
{target:`Where can I find [product]?`, content:`[商品] はどこで見つかりますか？`},
{target:`What's the return policy?`, content:`返品ポリシーは何ですか？`},
{target:`Are there any additional fees?`, content:`他に追加の料金はありますか？`},
{target:`Can I try this on?`, content:`これを試着してもいいですか？`},
{target:`Are there any promotions today?`, content:`今日は何かキャンペーンがありますか？`},
{target:`Do you have this in a different color/size?`, content:`これは他の色／サイズでもありますか？`},
{target:`Where is the fitting room?`, content:`試着室はどこですか？`},
{target:`Can you help me find [specific brand]?`, content:`[特定のブランド] を探すのを手伝ってもらえますか？`},
{target:`Is there a warranty on this product?`, content:`この商品には保証がついていますか？`},
{target:`Can I get a discount if I buy more than one?`, content:`複数購入すると割引がありますか？`},
{target:`Do you offer gift wrapping?`, content:`ギフト包装はありますか？`},
{target:`What forms of payment do you accept?`, content:`どの支払い方法を受け付けていますか？`},
{target:`Is there a loyalty program?`, content:`ロイヤリティプログラムはありますか？`},
{target:`Are there any salespeople available to assist me?`, content:`私をサポートしてくれるセールスマンはいますか？`},
{target:`Can I get a bag for these items?`, content:`これらのアイテムに袋をもらえますか？`},
{target:`How long is the warranty valid?`, content:`保証期間はどれくらいですか？`},
{target:`Are there any special offers for members?`, content:`会員向けの特別なオファーはありますか？`},
{target:`Is there a cash discount?`, content:`現金払いの割引はありますか？`},
{target:`Are there any sales tax charges?`, content:`消費税がかかりますか？`},
{target:`Can I return this if it doesn't fit?`, content:`サイズが合わない場合、これは返品できますか？`},
{target:`Are there any installment payment options?`, content:`分割払いの選択肢はありますか？`},
{target:`Can you recommend similar products?`, content:`似たような商品をお勧めしてもらえますか？`},
{target:`Is this the latest model/version?`, content:`これは最新のモデル／バージョンですか？`},
{target:`Do you have a customer loyalty program?`, content:`お客様向けの忠誠度プログラムはありますか？`},
{target:`Can I get a refund if I change my mind?`, content:`思い直した場合、返金は可能ですか？`},
{target:`What's the room rate per night?`, content:`1泊の宿泊料金はいくらですか？`},
{target:`Is breakfast included in the room rate?`, content:`朝食は宿泊料金に含まれていますか？`},
{target:`Can I have a room with a view?`, content:`眺めの良い部屋をお願いできますか？`},
{target:`What time is check-in/check-out?`, content:`チェックイン／チェックアウトは何時ですか？`},
{target:`Can I get a wake-up call?`, content:`起床のお知らせをお願いできますか？`},
{target:`Is there free Wi-Fi in the rooms?`, content:`部屋で無料のWi-Fiはありますか？`},
{target:`Do you have parking available?`, content:`駐車場はありますか？`},
{target:`Can I pay with a credit card?`, content:`クレジットカードで支払えますか？`},
{target:`Is there a shuttle service to the airport?`, content:`空港へのシャトルサービスはありますか？`},
{target:`Are pets allowed in the hotel?`, content:`ペットはホテル内に入れますか？`},
{target:`Can I request a non-smoking room?`, content:`禁煙の部屋をリクエストできますか？`},
{target:`How far is the hotel from [landmark]?`, content:`ホテルは［名所］からどれくらいの距離ですか？`},
{target:`Are there any additional fees or taxes?`, content:`他に追加の料金や税金はありますか？`},
{target:`Can I store my luggage before check-in or after check-out?`, content:`チェックイン前やチェックアウト後に荷物を預けることはできますか？`},
{target:`Is there a gym or fitness center in the hotel?`, content:`ホテル内にはジムやフィットネスセンターがありますか？`},
{target:`What amenities are included in the room?`, content:`部屋にはどのような設備が含まれていますか？`},
{target:`Can I have extra towels/toiletries?`, content:`タオルやアメニティを追加してもらえますか？`},
{target:`Is room service available 24/7?`, content:`24時間ルームサービスは利用可能ですか？`},
{target:`Can you recommend any good local restaurants?`, content:`おすすめの地元のレストランはありますか？`},
{target:`How do I connect to the hotel's Wi-Fi?`, content:`ホテルのWi-Fiに接続する方法は？`},
{target:`Can I extend my stay for an extra night?`, content:`宿泊を追加できますか？`},
{target:`Is there a pool or spa in the hotel?`, content:`ホテルにはプールやスパがありますか？`},
{target:`Can I cancel or modify my reservation?`, content:`予約のキャンセルや変更は可能ですか？`},
{target:`Do you provide a complimentary breakfast?`, content:`朝食は無料で提供されますか？`},
{target:`What is the hotel's cancellation policy?`, content:`ホテルのキャンセルポリシーは何ですか？`},
{target:`Can I request a late check-out?`, content:`レイトチェックアウトをリクエストできますか？`},
{target:`Is there a business center with printing services?`, content:`ビジネスセンターと印刷サービスはありますか？`},
{target:`Can you recommend any nearby attractions or sightseeing spots?`, content:`近くの観光スポットや見所をお勧めしてもらえますか？`},
{target:`Is there a bar or lounge in the hotel?`, content:`ホテルにはバーまたはラウンジがありますか？`},
{target:`Can you arrange transportation for me to [destination]?`, content:`[目的地] への移動手段を手配してもらえますか？`},
{target:`May I see the menu, please? `, content:`メニューを見せていただけますか？`},
{target:`What's the special of the day? `, content:`今日のおすすめは何ですか？`},
{target:`I'll have the chef's special. `, content:`シェフのおすすめをお願いします。`},
{target:`Can I get a table for two? `, content:`二人用のテーブルをお願いできますか？`},
{target:`Is this seat taken? `, content:`この席は埋まっていますか？`},
{target:`I'd like to make a reservation. `, content:`予約をしたいのですが。`},
{target:`What's the soup of the day? `, content:`今日のスープは何ですか？`},
{target:`I'm ready to order. `, content:`注文をします。`},
{target:`Can I have a glass of water, please? `, content:`水を一杯お願いします。`},
{target:`I'm allergic to nuts. `, content:`私はナッツアレルギーがあります。`},
{target:`How spicy is this dish? `, content:`この料理はどれくらい辛いですか？`},
{target:`Can I substitute the fries for a salad? `, content:`フライをサラダに変えてもらえますか？`},
{target:`What do you recommend for dessert? `, content:`デザートは何がおすすめですか？`},
{target:`Is service charge included? `, content:`サービス料は含まれていますか？`},
{target:`Could we have the check, please? `, content:`お会計をお願いします。`},
{target:`The food was delicious! `, content:`料理はおいしかったですね！`},
{target:`This is too salty for my taste. `, content:`これは私の味には少ししょっぱすぎます。`},
{target:`I'll take the bill separately. `, content:`別々にお会計します。`},
{target:`Are you ready to order? `, content:`ご注文はお決まりですか？`},
{target:`Excuse me, we need more napkins. `, content:`すみません、もっとナプキンをください。`},
{target:`Is the tip included in the bill? `, content:`チップは請求書に含まれていますか？`},
{target:`Can I have a doggy bag for the leftovers? `, content:`残り物を持ち帰りできますか？`},
{target:`How long is the wait for a table? `, content:`テーブルの待ち時間はどれくらいですか？`},
{target:`The check, please. `, content:`お会計をお願いします。`},
{target:`What's the house specialty? `, content:`お店の特別メニューは何ですか？`},
{target:`Is it possible to split the bill? `, content:`請求書を分けてもらえますか？`},
{target:`Can I have the dressing on the side? `, content:`ドレッシングは別にしてもらえますか？`},
{target:`The service here is excellent. `, content:`ここのサービスは素晴らしいですね。`},
{target:`Is there a vegetarian option? `, content:`ベジタリアン向けのオプションはありますか？`},
{target:`This is a bit overcooked. `, content:`これは少し焼きすぎです。`},
{target:`I'd like my steak medium rare. `, content:`ステーキはミディアムレアでお願いします。`},
{target:`Could I have some more bread, please? `, content:`もっとパンをください。`},
{target:`Is there a kids' menu available? `, content:`子供向けのメニューはありますか？`},
{target:`I'll go with the daily special. `, content:`今日の日替わりメニューにします。`},
{target:`How much is the corkage fee? `, content:`キャンセル料はいくらですか？`},
{target:`This dish is a bit too bland. `, content:`この料理は少し味気ないです。`},
{target:`Do you have any recommendations for wine? `, content:`ワインのおすすめはありますか？`},
{target:`Could I have a refill, please? `, content:`もう一杯おかわりできますか？`},
{target:`I'd like to order dessert now. `, content:`今、デザートを注文します。`},
{target:`Is the gratuity included in the bill? `, content:`チップは請求書に含まれていますか？`},
{target:`This dish is too spicy for me. `, content:`この料理は私には辛すぎます。`},
{target:`Could we have the dessert menu? `, content:`デザートのメニューを見せていただけますか？`},
{target:`I'll have the same as her/him. `, content:`彼/彼女と同じものをください。`},
{target:`I'm not satisfied with this dish. `, content:`この料理には満足していません。`},
{target:`How is the fish cooked? `, content:`この魚はどのように調理されていますか？`},
{target:`The portion size is too small. `, content:`ポーションが小さすぎます。`},
{target:`Can I get some more ice, please? `, content:`もっと氷をください。`},
{target:`The food presentation is impressive. `, content:`料理のプレゼンテーションが素晴らしいです。`},
{target:`I'll have my coffee black. `, content:`コーヒーはブラックでお願いします。`},
{target:`Are there any house specialties? `, content:`お店の特別メニューはありますか？`},
{target:`Hey! How have you been?`, content:`ねえ！最近どうだった？`},
{target:`What's new with you?`, content:`最近何か新しいことあった？`},
{target:`Let's catch up over coffee.`, content:`コーヒーでも飲みながら近況を話そうよ。`},
{target:`I heard you went on a trip. How was it?`, content:`旅行に行ったって聞いたよ。どうだったの？`},
{target:`Do you want to hang out this weekend?`, content:`今週末一緒に遊びに行かない？`},
{target:`I watched this amazing movie last night.`, content:`昨晩、すごい映画を見たんだ。`},
{target:`Have you tried that new restaurant downtown?`, content:`最近できたダウンタウンの新しいレストラン行ったことある？`},
{target:`I can't believe it's been so long since we last met.`, content:`最後に会ったのがこんなに長い間前だなんて信じられない。`},
{target:`What do you feel like doing tonight?`, content:`今夜は何かしたいことある？`},
{target:`Did you hear about [news/event]?`, content:`[ニュース／イベント] 聞いたことある？`},
{target:`Let's plan a movie night at my place.`, content:`うちで映画の夜を計画しようよ。`},
{target:`I have some exciting news to share!`, content:`分かち合いたい興奮するようなニュースがあるんだ！`},
{target:`How's work going for you lately?`, content:`最近の仕事、どうなの？`},
{target:`Guess what happened to me today!`, content:`今日、なんと起こったか当ててみて！`},
{target:`We should definitely go on a trip together sometime.`, content:`絶対に一緒に旅行に行かなきゃね。`},
{target:`I started a new hobby. It's so much fun!`, content:`新しい趣味始めたんだ。すごく楽しいよ！`},
{target:`Can you recommend any good books to read?`, content:`良い本あれば教えてくれない？`},
{target:`I need your advice on something.`, content:`ちょっとアドバイスが欲しいんだけど。`},
{target:`Do you want to join me for lunch tomorrow?`, content:`明日ランチ一緒に行かない？`},
{target:`I can't stop listening to this new song. You should check it out!`, content:`この新しい曲がやめられないんだ。聞いてみるべきだよ！`},
{target:`Let's plan a game night with the gang.`, content:`仲間とゲームの夜を計画しよう。`},
{target:`I'm thinking of redecorating my place. Any ideas?`, content:`部屋をリフォームしようと思ってるんだ。アイデアある？`},
{target:`Did you see that hilarious meme I sent you?`, content:`送った面白いミーム見た？`},
{target:`I'm so excited about the upcoming concert.`, content:`来週のコンサートが楽しみでたまらない。`},
{target:`Let's plan a beach day this weekend.`, content:`今週末ビーチデーを計画しよう。`},
{target:`I can't believe summer is almost over. Time flies!`, content:`もう夏も終わりか。時が経つのは早いね！`},
{target:`How's your family doing?`, content:`家族は元気？`},
{target:`We should try that new cafe everyone's talking about.`, content:`みんなが話題にしてる新しいカフェ試してみない？`},
{target:`I need a good laugh. Let's watch a comedy tonight.`, content:`笑いが必要だ。今夜はコメディを見よう。`},
{target:`Thanks for always being there for me. You're the best!`, content:`いつもそばにいてくれてありがとう。最高だよ！`},
{target:`Good morning! How are you today?`, content:`おはようございます！今日はいかがですか？`},
{target:`I hope you had a good weekend.`, content:`週末は良かったですか？`},
{target:`Could you please pass me the agenda for today's meeting?`, content:`今日のミーティングの議題を渡していただけますか？`},
{target:`Do you have a moment to discuss the new project?`, content:`新しいプロジェクトについて少し話す時間はありますか？`},
{target:`Let's schedule a team meeting to go over the quarterly results.`, content:`四半期の成績を確認するためにチームミーティングを予定しましょう。`},
{target:`I appreciate your input during the brainstorming session.`, content:`ブレーンストーミングセッションでのご意見、ありがとうございます。`},
{target:`Can you provide an update on your current tasks?`, content:`現在進行中のタスクについてアップデートしていただけますか？`},
{target:`We need to meet our deadlines. Let's prioritize tasks.`, content:`締切を守る必要があります。タスクの優先順位をつけましょう。`},
{target:`I'll send you the report by the end of the day.`, content:`今日中にレポートを送ります。`},
{target:`How's the progress on the client project?`, content:`クライアントのプロジェクトの進捗はどうですか？`},
{target:`I'd like to propose a new strategy for the marketing campaign.`, content:`マーケティングキャンペーンの新しい戦略を提案したいと思います。`},
{target:`Can we schedule a one-on-one meeting to discuss your goals?`, content:`目標について話すために1対1のミーティングを予定できますか？`},
{target:`We need to address the issue before it becomes a bigger problem.`, content:`大きな問題になる前にこの問題に対処する必要があります。`},
{target:`I appreciate your collaboration on this project.`, content:`このプロジェクトでのご協力、感謝しています。`},
{target:`Let's set up a conference call to include our remote team members.`, content:`リモートチームメンバーを含めた会議のセッティングをしましょう。`},
{target:`I'll handle the logistics for the upcoming event.`, content:`来るイベントのロジスティクスは私が担当します。`},
{target:`Can you provide some insights into the market trends?`, content:`市場のトレンドについていくつかの洞察を教えていただけますか？`},
{target:`It's essential to maintain open communication within the team.`, content:`チーム内でオープンなコミュニケーションを保つことは重要です。`},
{target:`Let's collaborate to find a solution to this challenge.`, content:`この課題に対する解決策を見つけるために協力しましょう。`},
{target:`I'll forward you the relevant documents for your review.`, content:`レビュー用に関連する文書を転送します。`},
{target:`We can schedule a training session for the new software.`, content:`新しいソフトウェアのトレーニングセッションを予定できます。`},
{target:`Your feedback is crucial for the improvement of our processes.`, content:`あなたのフィードバックはプロセスの改善に不可欠です。`},
{target:`I recommend reaching out to the client to address their concerns.`, content:`クライアントに連絡して、彼らの懸念事項に対処することをお勧めします。`},
{target:`Let's organize a team-building activity for next month.`, content:`来月、チームビルディングのアクティビティを企画しましょう。`},
{target:`Could you clarify your expectations regarding this project?`, content:`このプロジェクトに関するあなたの期待を明確にしていただけますか？`},
{target:`We should acknowledge the hard work of our team members.`, content:`チームメンバーの頑張りを認めるべきです。`},
{target:`I suggest creating a detailed project timeline.`, content:`詳細なプロジェクトのタイムラインを作成することを提案します。`},
{target:`Let's plan a team outing to celebrate our recent successes.`, content:`最近の成功を祝うためにチームの外出を計画しましょう。`},
{target:`I'll handle the paperwork for the upcoming client presentation.`, content:`来るクライアントプレゼンテーションのための書類は私が担当します。`},
{target:`It's important to maintain a positive work environment.`, content:`ポジティブな職場環境を維持することが重要です。`},
{target:`I'm not sure about that.`, content:`それについてはよくわからないんです。`},
{target:`It's up in the air right now.`, content:`今のところ未定です。`},
{target:`Let's play it by ear.`, content:`その場の流れで決めましょう。`},
{target:`I'll see how things go.`, content:`事の進行具合を見ます。`},
{target:`That's a possibility.`, content:`それは可能性があります。`},
{target:`I might consider it.`, content:`検討してみるかもしれません。`},
{target:`We'll see what happens.`, content:`何が起こるか見てみましょう。`},
{target:`It's a bit unclear at the moment.`, content:`現時点では少し不透明です。`},
{target:`I haven't made up my mind yet.`, content:`まだ決めていません。`},
{target:`I'll think about it.`, content:`考えてみます。`},
{target:`I don't have a definite answer.`, content:`明確な答えがありません。`},
{target:`It's still under consideration.`, content:`まだ検討中です。`},
{target:`I'm open to suggestions.`, content:`提案にはオープンです。`},
{target:`It's a gray area.`, content:`これは微妙な問題です。`},
{target:`I'm on the fence.`, content:`どちらにするか迷っています。`},
{target:`I haven't committed to anything yet.`, content:`まだ何にも決めていません。`},
{target:`There's some ambiguity.`, content:`ある程度曖昧さがあります。`},
{target:`I'm not entirely convinced.`, content:`完全に納得していません。`},
{target:`It's still up for debate.`, content:`まだ議論の余地があります。`},
{target:`I don't want to jump to conclusions.`, content:`結論を急ぎたくありません。`},
{target:`It's not set in stone.`, content:`まだ確定していません。`},
{target:`There's room for interpretation.`, content:`解釈の余地があります。`},
{target:`I'll keep my options open.`, content:`選択肢をオープンにしておきます。`},
{target:`I haven't ruled it out completely.`, content:`完全には否定していません。`},
{target:`It's a bit of a gray area.`, content:`これは少し微妙な問題です。`},
{target:`I haven't figured it out yet.`, content:`まだそれを解明していません。`},
{target:`I'll go with the flow.`, content:`流れに任せます。`},
{target:`I'm not leaning either way.`, content:`片方に傾いていません。`},
{target:`It's still in the exploration phase.`, content:`まだ探索段階です。`},
{target:`I need more information before deciding.`, content:`決断する前にもっと情報が必要です。`},
{target:`It's not crystal clear.`, content:`完全には明確ではありません。`},
{target:`I'm keeping it open-ended.`, content:`結論を出さずにおきます。`},
{target:`I'm taking a wait-and-see approach.`, content:`様子を見るスタンスです。`},
{target:`I haven't gotten around to deciding.`, content:`まだ決める段階に至っていません。`},
{target:`I'm still feeling it out.`, content:`まだ感触を探っています。`},
{target:`I'll need more time to think about it.`, content:`もっと時間がかかりそうです。`},
{target:`It's a bit hazy right now.`, content:`今は少し曖昧です。`},
{target:`I haven't made a firm decision.`, content:`しっかりとした決断はしていません。`},
{target:`I'm exploring my options.`, content:`選択肢を探っています。`},
{target:`I'm in the process of deciding.`, content:`決断の途中です。`},
{target:`I'm not entirely clear on that.`, content:`それについて完全には理解していません。`},
{target:`I'm still in the contemplation stage.`, content:`まだ考慮の段階にいます。`},
{target:`I'll see how things pan out.`, content:`事の進行を見ます。`},
{target:`I'm still weighing the pros and cons.`, content:`利点と欠点を考えています。`},
{target:`I'll decide when the time is right.`, content:`時が来たら決めます。`},
{target:`It's a bit of a puzzle to me.`, content:`これは少し謎めいています。`},
{target:`I haven't cracked that nut yet.`, content:`それはまだ解決できていません。`},
{target:`I'm playing it safe for now.`, content:`今のところ安全を確保しています。`},
{target:`I'm still on the fence about it.`, content:`それについてはまだ迷っています。`},
{target:`I'll need to mull it over.`, content:`それを考え込む必要があります。`},
]
